import 'package:base_flutter/landing/home/models/post/post_model.dart';
import 'package:base_flutter/landing/home/models/user/user_model.dart';
import 'package:base_flutter/shared/widgets/custom_widgets/custom_widgets.dart';
import 'package:base_flutter/shared/widgets/custom_widgets/widgets/General.dart';
import 'package:base_flutter/shared/widgets/default_appbar.dart';
import 'package:flutter/material.dart';
import 'package:tf_validator/tf_validator.dart';
part 'details_data.dart';
part 'details.dart';
